"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { AnimatePresence, motion } from "motion/react";
import { ArrowUpRight, BriefcaseBusiness, Menu, ShoppingBag, UserRound, X } from "lucide-react";
import { ThemeToggle } from "./theme-toggle";

const LINKS = [{ href: "/projects", label: "Work", icon: BriefcaseBusiness }, { href: "/ventures", label: "Ventures", icon: ArrowUpRight }, { href: "/shop", label: "Shop", icon: ShoppingBag }, { href: "/about", label: "About", icon: UserRound }, { href: "/contact", label: "Contact", icon: ArrowUpRight }];
export function Nav({ logoUrl, logoScale = 100, logoRadius = 10 }: { logoUrl?: string; logoScale?: number; logoRadius?: number }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const update = () => setScrolled(window.scrollY > 16); update(); window.addEventListener("scroll", update, { passive: true }); return () => window.removeEventListener("scroll", update); }, []);
  useEffect(() => setOpen(false), [pathname]);
  const logo = <>{logoUrl ? <span className="grid h-7 w-7 overflow-hidden" style={{ borderRadius: `${logoRadius}px` }}><img src={logoUrl} alt="Joshua Ugwu" className="h-full w-full object-contain" style={{ transform: `scale(${logoScale / 100})` }} /></span> : <span className="grid h-7 w-7 place-items-center rounded-lg bg-fg text-xs text-bg">JZ</span>}<span className="brand-wordmark">buildwith<span className="brand-zaza">zaza</span></span></>;
  return <header className={`sticky top-0 z-50 transition-all duration-300 ${scrolled ? "border-b border-border bg-bg/90 backdrop-blur-xl" : "bg-bg/70 backdrop-blur-md"}`}><div className="mx-auto flex h-[4.7rem] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" className="focus-ring flex items-center gap-2 font-display text-base font-bold tracking-[-.04em] text-fg">{logo}</Link><nav className="hidden items-center gap-7 md:flex">{LINKS.map((link) => { const active = pathname === link.href || (link.href === "/projects" && pathname.startsWith("/projects/")); return <Link key={link.href} href={link.href} className={`focus-ring relative text-sm font-semibold ${active ? "text-fg" : "text-fg-muted hover:text-fg"}`}>{link.label}{active && <motion.span layoutId="active-nav" className="absolute -bottom-2 left-0 h-0.5 w-full bg-brand" />}</Link>; })}</nav><div className="flex items-center gap-2"><ThemeToggle /><Link href="/hire" className="button-primary !hidden min-h-10 px-4 md:!inline-flex">Let&apos;s work <ArrowUpRight size={15} /></Link><button type="button" onClick={() => setOpen((value) => !value)} aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} className="focus-ring grid h-10 w-10 place-items-center rounded-xl border border-border bg-surface md:hidden">{open ? <X size={19} /> : <Menu size={19} />}</button></div></div><AnimatePresence>{open && <motion.div initial={{ opacity: 0, clipPath: "inset(0 0 100% 0)" }} animate={{ opacity: 1, clipPath: "inset(0 0 0% 0)" }} exit={{ opacity: 0, clipPath: "inset(0 0 100% 0)" }} transition={{ duration: .28, ease: [0.16, 1, .3, 1] }} className="absolute inset-x-0 top-full border-b border-border bg-bg/95 p-4 shadow-2xl backdrop-blur-xl md:hidden"><nav className="mx-auto grid max-w-7xl gap-2" aria-label="Mobile navigation">{LINKS.map(({href,label,icon: Icon}, index) => <motion.div key={href} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .06 + index * .04 }}><Link href={href} className={`flex items-center justify-between rounded-2xl px-4 py-3.5 text-base font-bold ${pathname === href ? "bg-fg text-bg" : "bg-surface text-fg"}`}><span className="flex items-center gap-3"><Icon size={17} />{label}</span><ArrowUpRight size={16} /></Link></motion.div>)}<Link href="/hire" className="button-primary mt-2">Start a project <ArrowUpRight size={16} /></Link></nav></motion.div>}</AnimatePresence></header>;
}
