"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Search } from "lucide-react";
import type { Project, ProjectCategory } from "@/lib/data/projects";
import { ProjectCover } from "./project-cover";

const FILTERS: { label: string; value: ProjectCategory | "all" }[] = [{ label: "All work", value: "all" }, { label: "Client work", value: "client" }, { label: "Products", value: "product" }, { label: "Ventures", value: "venture" }, { label: "Collaborations", value: "collaboration" }];
export function ProjectsGrid({ projects }: { projects: Project[] }) { const [filter, setFilter] = useState<ProjectCategory | "all">("all"); const [query, setQuery] = useState(""); const visible = useMemo(() => projects.filter((project) => (filter === "all" || project.category === filter) && (!query || `${project.title} ${project.summary} ${project.stack.join(" ")}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b) => a.order - b.order), [projects, filter, query]); return <><div className="mt-10 flex flex-col justify-between gap-4 border-y border-border py-4 sm:flex-row sm:items-center"><div className="flex flex-wrap gap-2">{FILTERS.map((item) => <button key={item.value} type="button" onClick={() => setFilter(item.value)} className={`focus-ring rounded-lg px-3 py-2 text-sm font-semibold transition ${filter === item.value ? "bg-fg text-bg" : "text-fg-muted hover:bg-surface-raised hover:text-fg"}`}>{item.label}</button>)}</div><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-fg-muted" size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search work" className="focus-ring w-full rounded-xl border border-border bg-surface py-2.5 pl-9 pr-4 text-sm sm:w-56" /></label></div>{visible.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visible.map((project, index) => <Link key={project.slug} href={`/projects/${project.slug}`} className="group rounded-[1.3rem] border border-border bg-surface p-3 transition hover:-translate-y-1 hover:border-brand hover:shadow-xl"><ProjectCover project={project} index={index}/><div className="p-2 pb-3 pt-5"><div className="flex justify-between gap-3"><span className="font-mono text-[.65rem] font-semibold uppercase tracking-[.13em] text-fg-muted">{project.category}</span><ArrowUpRight size={17} className="text-fg-muted group-hover:text-brand" /></div><h2 className="mt-2 font-display text-xl font-bold tracking-[-.045em]">{project.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-fg-muted">{project.summary}</p></div></Link>)}</div> : <p className="py-20 text-center text-fg-muted">No work matches that search yet.</p>}</>; }
